name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy_firebase:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4  # Gets firebase.json and .firebaserc
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Choose ONE of these authentication methods:
      # Option 1: Using FIREBASE_TOKEN (simpler)
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        
      # OR Option 2: Using service account JSON (more complex)
      # - name: Set up Google Cloud Auth
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #
      # - name: Deploy to Firebase
      #   run: firebase deploy --only hosting
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/service-account.json"

  deploy_gh_pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist